# Generated by Django 3.2 on 2022-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='businessFuncId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='countryId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='roleId',
            field=models.IntegerField(default=0),
        ),
    ]
