# Generated by Django 3.2 on 2022-04-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterApi', '0005_scopemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopemaster',
            name='updatedBy',
        ),
    ]
