# Generated by Django 3.2 on 2022-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApi', '0008_operatormaster_scopemasterid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductgranularityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productgranularityfilterName', models.CharField(max_length=180)),
                ('productgranularityfilterCode', models.CharField(max_length=10)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
