# Generated by Django 3.2 on 2022-04-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRepo',
            fields=[
                ('experimentId', models.AutoField(primary_key=True, serialize=False)),
                ('experimentName', models.CharField(max_length=100, unique=True)),
                ('measurementStartDate', models.DateTimeField(auto_now_add=True)),
                ('measurementEndDate', models.DateTimeField(auto_now_add=True)),
                ('testStartDate', models.DateTimeField(auto_now_add=True)),
                ('testEndDate', models.DateTimeField(auto_now_add=True)),
                ('referenceEndDate', models.DateTimeField(auto_now_add=True)),
                ('referenceStartDate', models.DateTimeField(auto_now_add=True)),
                ('hypothesis', models.CharField(max_length=100)),
                ('numberOfGroups', models.PositiveIntegerField()),
                ('isCostAssociated', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('experimentOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
