# Generated by Django 3.2 on 2022-04-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterApi', '0004_constraintmaster_marketmaster_measuremaster_productgranularitymaster_spacialgranularitymaster'),
        ('expRepo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('factorId', models.AutoField(primary_key=True, serialize=False)),
                ('factorName', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessMetric',
            fields=[
                ('successMetricId', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
                ('measureMasterId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.measuremaster')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeFilters',
            fields=[
                ('scopeFilterId', models.AutoField(primary_key=True, serialize=False)),
                ('scopeFilterValue', models.CharField(max_length=200)),
                ('scopeFilterOperator', models.CharField(max_length=200)),
                ('scopeFilterOperation', models.CharField(max_length=200)),
                ('isFirstSelected', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
                ('scopeFilterMasterId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.scopemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('levelId', models.AutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=200)),
                ('levelDescription', models.CharField(max_length=400)),
                ('levelCost', models.PositiveIntegerField()),
                ('levelpercentageAssign', models.PositiveIntegerField()),
                ('isControlGroup', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
                ('factorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.factor')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('groupDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=200)),
                ('groupDescription', models.CharField(max_length=400)),
                ('costPerExperiment', models.PositiveIntegerField()),
                ('percentageAllocation', models.PositiveIntegerField()),
                ('isControlGroup', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
            ],
        ),
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('constraintId', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('isDelete', models.BooleanField(blank=True, default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('constraintMasterId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.constraintmaster')),
                ('expRepoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
            ],
        ),
    ]
