# Generated by Django 3.2 on 2022-04-19 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expRepo', '0002_constraints_factor_groupdetails_levels_scopefilters_successmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentrepo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 19, 10, 43, 25, 465935, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='measurementEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='measurementStartDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='referenceEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='referenceStartDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='testEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experimentrepo',
            name='testStartDate',
            field=models.DateField(),
        ),
    ]
