# Generated by Django 3.2 on 2022-04-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expRepo', '0003_auto_20220419_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levels',
            old_name='levelpercentageAssign',
            new_name='levelPercentageAssign',
        ),
    ]
