# Generated by Django 3.2 on 2022-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expRepo', '0005_auto_20220425_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentrepo',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
