# Generated by Django 3.2 on 2022-04-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expRepo', '0006_experimentrepo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimentcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exprepoid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expRepo.experimentrepo')),
            ],
        ),
    ]
