# Generated by Django 3.2 on 2022-04-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expRepo', '0007_experimentcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experimentcount',
        ),
    ]
